auth_app/urls.py
from django.urls import path

from auth_app import views

app_name = 'auth_app'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

intro/urls.py
from django.contrib import admin
from django.urls import path, include

from hello import views

urlpatterns = [
    path('', include('hello.urls')),
    path('admin/', admin.site.urls),
    path('hello/', views.hello),
    path('hellogeorge/', views.hello_george),
    path('hi/', views.hi),
    path('next/', include('next_app.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form/', include('form_app.urls')),
    path('form2/', include('form_app2.urls')),
    path('form3/', include('form_app3.urls')),
    path('form4/', include('form_app4.urls')),
    path('form5/', include('form_app5.urls')),
    path('crud/', include('crud_app.urls')),
    path('relations/', include('relations_app.urls')),
    path('message/', include('message_app.urls')),
    path('view/', include('view_app.urls')),
    path('state/', include('state_app.urls')),
    path('auth/', include('auth_app.urls')),
    path('dogs/', include('api_app.urls')),

]

auth_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login, logout

User = get_user_model()


def index(request):
    users = User.objects.all()
    print(users)

    # User.objects.create_user(username='test4', password='tajne')

    user = authenticate(username='admin', password='admin')

    if user:
        login(request, user=user)

    logout(request)

    return render(
        request,
        'auth_app/index.html'
    )


def login_view(request):
    if request.method == "GET":
        print(request.user)
        return render(
            request,
            'auth_app/login.html'
        )
    if request.method == "POST":
        data = request.POST
        username = data.get("username")
        password = data.get("password")

        user = authenticate(username=username, password=password)

        if user:
            login(request, user=user)

        return redirect('auth_app:login')


def logout_view(request):
    logout(request)

    return redirect('auth_app:login')

auth_app/templates/auth_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
OK
</body>
</html>

auth_app/templates/auth_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if user.is_authenticated %}
<h1>Witaj {{ user.username}}</h1>
<a href="{% url 'auth_app:logout' %}"><button>Wyloguj</button></a>
{% else %}
<form method="POST">{% csrf_token %}
  <input type="text" name="username" placeholder="Nazwa użytkownika">
  <input type="password" name="password" placeholder="Hasło">
  <input type="submit" value="Zaloguj">
    {% endif %}
</form>
</body>
</html>