hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

intro/urls.py
from django.contrib import admin
from django.urls import path, include

from hello import views

urlpatterns = [
    path('', include('hello.urls')),
    path('admin/', admin.site.urls),
    path('hello/', views.hello),
    path('hellogeorge/', views.hello_george),
    path('hi/', views.hi),
    path('next/', include('next_app.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form/', include('form_app.urls')),
    path('form2/', include('form_app2.urls')),
    path('form3/', include('form_app3.urls')),
    path('form4/', include('form_app4.urls')),
    path('form5/', include('form_app5.urls')),
    path('crud/', include('crud_app.urls')),
    path('relations/', include('relations_app.urls')),
    path('message/', include('message_app.urls')),
    path('view/', include('view_app.urls')),
    path('state/', include('state_app.urls')),
    path('auth/', include('auth_app.urls')),
    path('dogs/', include('api_app.urls')),

]

links/urls.py
from django.urls import path

from links import views

app_name = 'links'

urlpatterns = [
    path('first/', views.first, name='first'),
    path('second/', views.second, name='second'),
    path('third/<str:param>', views.third, name='third'),
]

links/views.py
from django.shortcuts import render


def first(request):
    return render(
        request,
        'links/first.html',
    )


def second(request):
    return render(
        request,
        'links/second.html',
    )


def third(request, param):
    return render(
        request,
        'links/third.html',
        context={
            'param': param
        }
    )

links/templates/links/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>To jest pierwsza strona </h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt ipsum
    nam repudiandae voluptate? Amet asperiores corporis cupiditate libero
    necessitatibus, neque nesciunt nihil nulla perferendis sed sit tempore
    tenetur, vel voluptates!</p>

    <p>Przejdź do strony <a href="{% url 'links:second' %}">drugiej</a></p>
</body>
</html>

links/templates/links/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>To jest druga strona </h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium
    adipisci architecto debitis dolor dolore eligendi eveniet ex, fugit in
    incidunt laborum odio officia quos reprehenderit repudiandae, veritatis
    voluptates. Fugiat, nesciunt.</p>

    <p>Przejdź do strony <a href="{% url 'links:third' 'abc'%}">trzeciej</a></p>
</body>
</html>

links/templates/links/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>To jest trzecia strona z parametrem {{ param }}</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab accusamus
      consectetur corporis cum, deleniti error fugiat itaque iusto molestiae
      odio odit perspiciatis praesentium quae quaerat qui reprehenderit
      sunt tempora vel.</p>

    <p>Przejdź do strony <a href="{% url 'links:first' %}">pierwszej</a></p>
</body>
</html>